version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.13
        environment:
          TEST_DB_USER: "postgres"
          TEST_DB_URL: "postgresql://root@localhost:5432"
      - image: circleci/postgres:9.6

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /go/src/github.com/obedtandadjaja/auth-go
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      # Test database set up
      - run: |
          echo "deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install postgresql-client-9.6
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "CREATE DATABASE auth_test;"

      - run: go mod download
      - run: go mod vendor

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run: make test
