apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-go{{ENV}}-deployment
  labels:
    app: auth-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-go
  template:
    metadata:
      labels:
        app: auth-go
    spec:
      containers:
        - name: auth-go{{ENV}}
          image: gcr.io/obedt-dev/auth-go:{{IMAGE_TAG}}
          envFrom:
            - configMapRef:
                name: auth-go{{ENV}}-env
            - secretRef:
                name: auth-go{{ENV}}-env
          readinessProbe:
            httpGet:
              path: "/health"
              port: 3000
            initialDelaySeconds: 2
            timeoutSeconds: 5
            periodSeconds: 6
            successThreshold: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: 150m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 220Mi
          ports:
            - containerPort: 3000
